###
GET http://localhost:4000/project

###

GET http://localhost:4000/project/2

###

POST http://localhost:4000/project
Content-Type: application/json

{
    "name": "The-good-corner",
    "resume": "wxcwxc",
    "img_url_1" : "cxwc",
    "img_url_2" : "wxcwx",
    "img_url_3" : "xcwxc",
    "img_url_4" : "xwcwxc",
    "technology_ids": [1,2],
    "github_link": "xcwxc"
}