###
GET http://localhost:4000/technology

###

GET http://localhost:4000/technology/1

###

POST http://localhost:4000/technology
Content-Type: application/json

{
    "name": "SQLite",
    "img_url": ""
}